name: fonz_music_flutter
description: A new Flutter project for Fonz 2.0, Fonz Music's 2nd app release.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#   for all buttons
  flutter_neumorphic: ^3.0.3
#  for all nfc functions
  nfc_in_flutter: ^2.0.5
#  for all api requests
  dio: ^4.0.0
#  all firebase
  firebase_crashlytics: ^2.0.6
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
#  to get the current version of the app to send to api
  package_info: ^0.4.0+16
#  to launch urls in app
  url_launcher: ^6.0.7
#  android version of keystore for access token + refresh
  flutter_secure_storage: ^4.2.1
#  android version of userDefaults for saving hasAccount, hasSpot, & hasConnectedCoasters
  shared_preferences: ^2.0.6
#  to support deep linking
  uni_links: ^0.5.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonzIcons/
    - assets/lightGreyIcons/
    - assets/darkGreyIcons/
    - assets/thirdParties/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MuseoSans-100
      fonts:
        - asset: fonts/MuseoSans-100.otf
    - family: MuseoSans-300
      fonts:
        - asset: fonts/MuseoSans-300.otf
    - family: MuseoSans-500
      fonts:
        - asset: fonts/MuseoSans-500.otf
    - family: MuseoSans-700
      fonts:
        - asset: fonts/MuseoSans-700.otf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
